# Default configuration for processing ROTSE-III science exposures
name: ROTSE-III Survey
Flavor: science
Program: supernova
# Heartbeat Period in seconds
Period: 5.0
# Time out in seconds
Timeout: 120.0
# Pipeline algorithms with relevant QAs
Pipeline: [Make_Subimages, Chooose_Refstars, Image_Differencing]
Algorithms:
    Make_Subimages:
        PixelRadius: 140
        QA: {}
    Choose_Refstars:
        QA: {}
    Image_Differencing:
        QA: {}

