# Default configuration for processing ROTSE-III science exposures
name: ROTSE-III Survey
Flavor: science
Program: supernova
# Heartbeat Period in seconds
Period: 5.0
# Time out in seconds
Timeout: 120.0
# Pipeline algorithms with relevant QAs
Pipeline: [Find_Data, Coaddition, Source_Extraction]
Algorithms:
    Find_Data:
        TimeBeforeDiscovery: 1 # months
        TimeAfterDiscovery: 2 # years
        QA: {}
    Coaddition:
        QA:
            Count_Pixels:
                PARAMS: {COUNT_NORMAL_RANGE: [-100.,100.], COUNT_WARN_RANGE: [-200.,200.], COUNT_REF: [10.]}
    Source_Extraction:
        QA: {}

