# Default configuration for processing ROTSE-III science exposures
name: ROTSE-III Survey
Flavor: science
Program: supernova
# Heartbeat Period in seconds
Period: 5.0
# Time out in seconds
Timeout: 120.0
# Pipeline algorithms with relevant QAs
Pipeline: [Find_Data, Coaddition, Source_Extraction, Make_Subimages, Image_Differencing, Choose_Refstars, Photometry]
Algorithms:
    Find_Data:
        TimeBeforeDiscovery: 1 # months
        TimeAfterDiscovery: 2 # years
        QA: {}
    Coaddition:
        QA:
            Count_Pixels:
                PARAMS: {COUNT_NORMAL_RANGE: [-1.5,1.5], COUNT_WARN_RANGE: [-2.0,2.0], COUNT_REF: [0.]}
    Source_Extraction:
        QA: {}
    Make_Subimages:
        PixelRadius: 140
        QA: {}
    Image_Differencing:
        QA: {}
    Choose_Refstars:
        QA: {}
    Photometry:
        QA: {}

