# Default configuration for processing ROTSE-III supernova data
name: ROTSE-III Survey
Flavor: science
Program: supernova
# Time out in seconds
Timeout: 600.0
# Pipeline algorithms with relevant QAs
Pipeline: [Find_Data, Coaddition, Source_Extraction, Make_Subimages, Image_Differencing, Choose_Refstars, Photometry]
Algorithms:
    Find_Data:
        TimeBeforeDiscovery: 1 # months
        TimeAfterDiscovery: 2 # years
        QA: {}
    Coaddition:
        QA:
            Count_Pixels:
                PARAMS: {COUNT_NORMAL_RANGE: [-100.,100.], COUNT_WARN_RANGE: [-200.,200.], COUNT_REF: [10.]}
    Source_Extraction:
        QA: {}
    Make_Subimages:
        PixelRadius: 140
        QA: {}
    Image_Differencing:
        QA: {}
    Choose_Refstars:
        QA: {}
    Photometry:
        QA: {}

