# Example Configuration to plot desired metrics

PAGE1:
    Title: RMS metrics after Coaddition
    noise: {TYPE: PATCH, VALS: NOISE, PLOT_TITLE: noise across sections of image, GRID: [2,2]}
    overscan_noise: {TYPE: PATCH, VALS: NOISE_OVERSCAN, PLOT_TITLE: overscan noise across sections of image, GRID: [2,2]}

PAGE2:
    Title: ROTSE light curve
    light_curve: {TYPE: 2DPLOT, XVALS: MJD, YVALS: MAG, PLOT_TITLE: Light Curve, XTITLE: MJD, YTITLE: ROTSE Magnitude}

